arrays in python.

In [1]:
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

# Printing type of array object
print("Array is of type:\n ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions:\n ", arr.ndim)

# Printing shape of array
print("Shape of array:\n ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array:\n ", arr.size)

# Printing type of elements in array
print("Array stores elements of type:\n ", arr.dtype)

Array is of type:
  <class 'numpy.ndarray'>
No. of dimensions:
  2
Shape of array:
  (2, 3)
Size of array:
  6
Array stores elements of type:
  int64


creating an array with a list and tuple

In [2]:
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]


arrays of fixed sizes

In [3]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("An array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("An array initialized with all 6s." 
            "Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("A random array:\n", e)

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.69688594 0.92695759]
 [0.04514638 0.63890605]]


creating an array using arange() function

In [5]:
##create a sequence of numbers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print("A sequential array of numbers with steps of 5:\n", f)

A sequential array of numbers with steps of 5:
 [ 0  5 10 15 20 25]


flatten arrays

In [ ]:
### flaten array
arr = np.array([[1, 2, 3] [4, 5, 6]])
flat_arr = arr.flatten()

print("Original array:\n", arr)
print("Flatten array:\n", flat_arr)